#pragma once

#define STONE_TYPE 0
#define WOODEN_TYPE 1
#define TERRAIN_TYPE 2
#define FURNITURE_TYPE 3
#define UNKNOWN_TYPE 4
#define PLANT_TYPE 5
#define FOOD_TYPE 6
#define TOOL_TYPE 7

#define EMPTY 0
#define STONE 1
#define GRASS 2
#define TREE_TRUNK 3
#define TREE_LEAVES 4
#define DIRT 5
#define WATER 6
#define SAND 7
#define NOKIUM 8
#define CLAY 9
#define THATCH 10
#define FIRE 11
#define CHARCOAL 12
#define ROCK_WALL 13
#define ROCKS 14
#define STICK 15
#define BRANCH 16
#define RED_BERRY_BUSH 17
#define RED_BUSH 18
#define RED_BERRY 19
#define SHARP_ROCK 20
#define SHARP_STICK 21
#define STONE_AXE 22
#define MOLTEN_ROCK 23
#define STEAM 24
#define RED_MUSHROOM 25
#define BLUE_BERRY_BUSH 26
#define BLUE_BERRIES 27
